org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
android.javaCompile.suppressSourceTargetDeprecationWarning=true

# Flutter SDK Versions
flutter.compileSdkVersion=36
flutter.minSdkVersion=21
flutter.targetSdkVersion=36
