// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrBZCDSwNKDA9MnxK5I6rlYlWCbY4G0FM',
    appId: '1:529823316324:web:1b873a06e78cde59a3a271',
    messagingSenderId: '529823316324',
    projectId: 'kerja-proyek-6f4dc',
    authDomain: 'kerja-proyek-6f4dc.firebaseapp.com',
    storageBucket: 'kerja-proyek-6f4dc.firebasestorage.app',
    measurementId: 'G-9K9GR9TDNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAgzVa5Ik5NswpwL-Weu1fplFrukJFuro',
    appId: '1:529823316324:android:e161e42318da9a4ca3a271',
    messagingSenderId: '529823316324',
    projectId: 'kerja-proyek-6f4dc',
    storageBucket: 'kerja-proyek-6f4dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKqTBq5fL_zM8CJtMeTGebsgcegE33jlg',
    appId: '1:529823316324:ios:9c208e7bba4363d6a3a271',
    messagingSenderId: '529823316324',
    projectId: 'kerja-proyek-6f4dc',
    storageBucket: 'kerja-proyek-6f4dc.firebasestorage.app',
    iosBundleId: 'com.example.billingApp',
  );
}
